import type { DocumentLocationTranslation } from "./document-locations";

export const documentLocationZh: Record<string, DocumentLocationTranslation> = {
  nacton: {
    region: "萨福克郡 · 奥威尔河口",
    period: "始新世与更新世",
    type: "河口潮间带",
    level: "谨慎成人 · 仅限低潮",
    local: "乘出租车前往 Orwell Park School／Nacton Shore 一带",
    walk: "从正式海岸入口经林间短步道抵达",
    duration: "2小时10分–2小时45分",
    route: ["从 Orwell Park 附近的公共入口沿林间步道前往岸边。", "只走坚实砾石和狭窄裸露前滩，不进入外侧泥滩。", "在小崖附近的松散 London Clay 岩块和冰川燧石中搜索。", "涨潮覆盖较坚实返程线之前原路返回。"],
    terrain: "林间步道 · 砾石 · 松软河口黏土",
    exit: "原林间入口；请做好位置标记",
    tideWindow: "退潮时前往，并为返程预留很大余量",
    season: "较干燥月份与稳定天气",
    conditions: "强降雨后或泥地饱水时不要前往",
    findTips: ["在细砾石和冲刷黏土中寻找有光泽的牙釉质。", "在松散黏土中寻找小牙齿、鳞片和椎骨。", "记录发现环境，并报告重要骨骼。", "冰川燧石中可能保留五瓣海胆壳或多孔海绵纹理。"],
    required: ["潮汐计划", "防水长靴", "手杖", "手机", "饮用水"],
    useful: ["手持放大镜", "小标本盒", "手套"],
    avoid: ["外侧泥滩", "挖掘崖壁", "敲击基岩", "独自前往"],
    hazards: ["深黏泥", "快速回涨的河口潮汐", "倒树", "藻类遮盖的软黏土"],
    safetyLead: "泥滩是这里最主要的危险，且曾发生致命陷困。只走坚实地面，与同伴同行并提早折返。",
    sssi: "Nacton Meadows 特别科学价值地点",
    rules: ["只采集松散材料。", "不得敲击基岩或挖掘崖壁。", "不得进入外侧泥滩。", "现场告示和土地管理方指示优先。"],
    source: "UK Fossils · Nacton 野外指南",
  },
  "fort-victoria": {
    region: "怀特岛 · 西怀特",
    period: "晚始新世",
    type: "潮汐海滩与砾石",
    level: "新手友好 · 可参加导览",
    local: "渡轮到 Yarmouth 后乘巴士、出租车或步行 30–40 分钟",
    walk: "从 Fort Victoria Country Park 内沿标识短路下到海滩",
    duration: "3小时15分–4小时",
    route: ["从 Yarmouth 沿海岸路线步行或乘当地交通前往 Fort Victoria Country Park。", "沿公园标识步道进入潮汐海滩。", "在松散砾石、黏土和潮线上寻找小型脊椎动物与贝类化石。", "潮水压缩可用海滩宽度前离开。"],
    terrain: "公园步道 · 砾石 · 湿滑黏土斑块",
    exit: "有标识的郊野公园海滩入口",
    tideWindow: "退潮至低潮时段",
    season: "全年天气平静时",
    conditions: "第一次前往最适合参加导览",
    findTips: ["在深色海滩碎屑中寻找致密、表面有凹点的骨骼。", "细砾石中小型有光泽碎片较显眼。", "始新世薄壳十分脆弱，应轻拿轻放。", "异常牙齿或骨骼应先记录并报告，再考虑清理。"],
    required: ["潮汐计划", "防滑鞋靴", "小标本罐", "饮用水"],
    useful: ["手持放大镜", "镊子", "导览预约"],
    avoid: ["游泳", "靠近强流区域", "挖掘崖壁"],
    hazards: ["强潮流", "湿滑黏土", "逐渐变窄的海滩", "脆弱标本"],
    safetyLead: "郊野公园很容易抵达，但海滩受潮汐影响，Fort Victoria 外海水流很强。不要游泳，并让儿童始终在近旁。",
    sssi: "Headon Warren and West High Down SSSI 海岸",
    rules: ["优先拾取松散前滩化石。", "不得挖掘崖壁或受保护地层。", "遵守公园告示和管理员指示。", "报告异常脊椎动物材料。"],
    source: "UK Fossils · 怀特岛郡议会",
  },
  "barton-on-sea": {
    region: "汉普郡 · Christchurch Bay",
    period: "中–晚始新世",
    type: "黏土崖与潮间带",
    level: "化石适合新手 · 崖壁风险高",
    local: "乘当地巴士或出租车到 Barton 崖顶",
    walk: "经正式海滩入口步行 10–20 分钟",
    duration: "2小时15分–2小时50分",
    route: ["使用正式崖顶步道和有标识的海滩入口。", "始终留在海滩高度，在松散黏土、砾石和海浪冲刷的滑坡物中搜索。", "发现脆弱贝壳后立即包裹。", "高潮前返程，绝不把新鲜滑坡当作捷径。"],
    terrain: "台阶或斜坡 · 砾石 · 黏稠黏土",
    exit: "抵达时使用的正式崖顶入口",
    tideWindow: "退潮时前往；避开风暴增水",
    season: "春至秋；避开潮湿风暴期",
    conditions: "温和侵蚀后较丰富，但需等待滑坡稳定",
    findTips: ["软黏土中可见细肋和高耸螺塔。", "连少量包裹黏土一起取出，并立即保护。", "在侵蚀黏土下方细砾石中寻找。", "松散材料中可见有光泽的牙齿与椎骨。"],
    required: ["潮汐计划", "防滑靴", "纸巾", "硬质标本盒", "饮用水"],
    useful: ["小铲", "手持放大镜", "护膝"],
    avoid: ["攀爬滑坡", "站在崖下", "强降雨后前往", "挖掘崖壁"],
    hazards: ["频繁崖体坍塌", "深黏泥", "涨潮", "极易碎的贝壳"],
    safetyLead: "留在海滩高度并远离崖脚。黏土滑坡可能毫无预警地移动，雨后风险尤其高。",
    sssi: "Highcliffe to Milford Cliffs 特别科学价值地点",
    rules: ["只采集自然侵蚀出的松散材料。", "不得攀爬或挖掘崖壁。", "脆弱贝壳只取少量。", "遵守最新现场告示。"],
    source: "UK Fossils · Barton-on-Sea 野外指南",
  },
  "warden-point": {
    region: "肯特郡 · 谢佩岛",
    period: "早始新世",
    type: "London Clay 潮间带",
    level: "适合有经验的潮汐规划者",
    local: "乘巴士或出租车前往 Warden／Leysdown",
    walk: "从公共海滩入口进入开阔前滩",
    duration: "2小时30分–3小时15分",
    route: ["从 Warden Bay 公共海滩入口进入。", "在松散结核、砾石和黏土平台上搜索，不处理崖面。", "避开裸露泥地和旧沉船残骸，即使看起来能缩短路线。", "在海滩仍然宽阔、入口仍清晰时折返。"],
    terrain: "砾石 · 黏土平台 · 黏稠泥地",
    exit: "Warden Bay 公共海滩入口",
    tideWindow: "退潮至低潮；提早返程",
    season: "春至秋天气稳定时",
    conditions: "强降雨或大型坍塌后不要立即前往",
    findTips: ["在冲刷砾石和松散黏土边缘搜索。", "结核中可能保存甲壳和螯。", "有凹点的骨骼应拍照并报告。", "结核中可见种子、木纹和叶片碎片。"],
    required: ["潮汐计划", "防水长靴", "手机", "手套", "饮用水"],
    useful: ["手杖", "手持放大镜", "标本盒"],
    avoid: ["挖掘崖壁", "外侧泥地", "旧沉船金属", "独自前往"],
    hazards: ["崖体坍塌", "深黏泥", "锋利沉船残骸", "潮水阻断"],
    safetyLead: "远离悬崖、泥滩和锋利沉船材料。最安全的安排是保守规划低潮窗口并提前折返。",
    sssi: "Sheppey Cliffs and Foreshore 特别科学价值地点",
    rules: ["不得挖掘崖壁或敲击基岩。", "只采集松散前滩材料。", "避免破坏植被和惊扰野生动物。", "重要脊椎动物发现应报告。"],
    source: "UK Fossils · Warden Point 野外指南",
  },
  "abbey-wood": {
    region: "大伦敦 · Bexley",
    period: "晚古新世–早始新世",
    type: "受管理的内陆化石层",
    level: "需事先许可 · 亲子友好",
    local: "步行前往 Lesnes Abbey Woods",
    walk: "从 Abbey Wood 车站步行 15–25 分钟",
    duration: "45分钟–1小时20分",
    route: ["采集前联系 Bexley Parks & Open Spaces，并等待许可。", "从 Abbey Wood 车站沿公共步道前往 Lesnes Abbey Woods。", "只使用指定化石层，并遵守管理员当天指示。", "浅挖、填回所有坑洞，并遵守允许带走的材料上限。"],
    terrain: "公园步道 · 土层挖掘区",
    exit: "沿 Lesnes Abbey 公园步道返回",
    tideWindow: "不受潮汐影响",
    season: "获得许可后前往；避开地面饱水时",
    conditions: "最适合参加经管理员批准或有组织的活动",
    findTips: ["在许可化石层中湿筛可找到深色小牙齿。", "细网筛配合镊子可处理微小有光泽材料。", "有凹点的骨片和甲片应记录。", "重要发现必须交给当地博物馆研究。"],
    required: ["书面许可", "0.5 毫米筛网", "水桶", "镊子", "标本罐"],
    useful: ["水盆", "两种孔径筛网", "跪垫"],
    avoid: ["未经批准前往", "挖深超过 2 英尺", "带走超过 2 公斤材料", "不回填坑洞"],
    hazards: ["未回填坑洞", "湿滑地面", "微小脆弱标本", "受保护科学地点"],
    safetyLead: "这里是受管理的公共化石层，不是随意挖掘点。先取得许可，并严格遵守管理员设定的限制。",
    sssi: "Abbey Wood 特别科学价值地点",
    rules: ["事先取得 Bexley Parks & Open Spaces 许可。", "挖掘深度不得超过 2 英尺。", "回填所有坑洞，带走材料不得超过 2 公斤。", "重要发现交由当地博物馆研究。"],
    source: "UK Fossils · Natural England Abbey Wood 指定资料",
  },
  "grange-chine": {
    region: "怀特岛 · 西南海岸",
    period: "早白垩世",
    type: "恐龙海岸潮间带",
    level: "建议第一次参加导览",
    local: "渡轮到 Ryde 或 West Cowes 后乘岛内巴士／出租车到 Brighstone",
    walk: "经 Grange Farm 的陡峭公共步道下到海滩",
    duration: "4小时–5小时",
    route: ["经 A3055／岛内巴士走廊抵达 Grange Farm，只使用合法停车位。", "沿公共步道穿过 chine，最后一段坡度较陡。", "在松散前滩材料和 chine 东侧植物碎屑层表面搜索。", "高潮前返回，避免岬角附近海滩被压缩。"],
    terrain: "陡坡 · 砾石 · 黏土岩台",
    exit: "穿过 Grange Farm 的公共步道",
    tideWindow: "退潮至低潮时段",
    season: "春至秋天气稳定时",
    conditions: "导览有助于确认入口和辨认化石",
    findTips: ["致密黑色骨骼内部可能呈蜂窝状；应记录产地。", "植物碎屑层中可见带木纹的碎片。", "在坚硬植物层表面的细碎屑中搜索。", "带凹点的甲片和致密骨骼需谨慎记录。"],
    required: ["潮汐计划", "防滑靴", "饮用水", "手机", "硬质标本盒"],
    useful: ["手持放大镜", "导览预约", "手杖"],
    avoid: ["挖掘崖壁", "站在新鲜坍塌物下方", "违规停车", "高潮时绕岬角"],
    hazards: ["陡峭海滩入口", "崖体坍塌", "潮水阻断", "不平整黏土岩台"],
    safetyLead: "公共步道可通行但较陡，海滩崖壁不稳定。远离崖脚，并围绕低潮规划返程。",
    sssi: "Compton Chine to Steephill Cove 特别科学价值地点",
    rules: ["只采集松散前滩材料。", "不得挖掘崖壁或原位恐龙层。", "使用公共步道和合法停车位。", "重要恐龙材料应报告 Dinosaur Isle。"],
    source: "Island Rivers · Wight Coast Fossils · GeoGuide",
  },
  hastings: {
    region: "东萨塞克斯郡 · Hastings 海岸",
    period: "早白垩世",
    type: "悬崖与潮间带",
    level: "适合有经验的采集者",
    local: "步行或乘当地巴士前往老城 Rock-a-Nore",
    walk: "从 Hastings 车站步行 20–30 分钟",
    duration: "2小时–2小时30分",
    route: ["穿过 Hastings 老城到 Rock-a-Nore，并使用正式海滨入口。", "在开阔前滩的松散黏土岩块中寻找牙齿、贝壳和植物材料。", "不得进入崩积物或在高耸砂岩崖下作业。", "潮水压缩路线前向 Rock-a-Nore 返回。"],
    terrain: "砾石 · 黏土斑块 · 岩石平台",
    exit: "Rock-a-Nore 海滨入口",
    tideWindow: "安全冲刷后的退潮时段",
    season: "秋至春天气稳定时",
    conditions: "发现数量高度依赖风暴后的海滩冲刷",
    findTips: ["足迹原位拍照；松散致密骨骼要记录环境。", "硬黏土岩块中可能含牙齿、鳞片和骨骼。", "冲刷黏土中寻找小型有光泽牙冠。", "松散岩块中可见碳化茎干与木材。"],
    required: ["潮汐计划", "安全帽", "防滑靴", "护目镜", "饮用水"],
    useful: ["手持放大镜", "标本盒", "带比例尺的相机"],
    avoid: ["崖脚", "崩积坡", "新鲜坍塌", "涨潮时绕岬角"],
    hazards: ["高大不稳定崖壁", "落石", "湿滑岩台", "潮水阻断"],
    safetyLead: "Rock-a-Nore 地质价值很高，但崖线危险。只搜索松散前滩材料，并与崖脚保持很大距离。",
    sssi: "Hastings Cliffs to Pett Beach 特别科学价值地点",
    rules: ["只采集松散前滩材料。", "不得挖掘崖壁、崩积物或基岩。", "遗迹化石原位拍照。", "重要恐龙或脊椎动物发现应报告。"],
    source: "UK Fossils · Hastings 野外指南",
  },
  "ardley-quarry": {
    region: "牛津郡 · Bicester 附近",
    period: "中侏罗世",
    type: "自然保护区与采石场剖面",
    level: "地质参观 · 采样需许可",
    local: "乘出租车到 BBOWT Ardley Wood Quarry 入口",
    walk: "保护区内有短距离起伏步道网络",
    duration: "1小时35分–2小时10分",
    route: ["只进入 BBOWT 公共自然保护区，不进入相邻活动采石场。", "沿有标识步道行走，远离陡坡和裸露岩壁。", "未获得 BBOWT 明确采样许可时，只作地质观察。", "所有受保护剖面和足迹都应保持原状。"],
    terrain: "较坚实起伏步道 · 南侧陡坡",
    exit: "经铁路桥旁的保护区入口返回",
    tideWindow: "不受潮汐影响",
    season: "全年开放；干燥白天最佳",
    conditions: "雨后保护区步道可能不平整",
    findTips: ["可观察松散石灰岩中的贝壳，但不得破坏岩壁。", "小型脊椎动物材料具有科研价值。", "未经书面许可不得移走材料。", "足迹属于受保护特征，只可观察和拍照。"],
    required: ["保护区地图", "防滑靴", "手机", "如需采样则带书面许可"],
    useful: ["望远镜", "相机", "手持放大镜"],
    avoid: ["活动采石场", "岩壁", "未经许可采样", "惊扰野生动物"],
    hazards: ["陡坡", "不平整采石场地面", "受保护剖面", "附近活动开采区"],
    safetyLead: "公共保护区虽然开放，但并不自动允许采集化石。留在保护区范围内，移走地质材料前取得书面许可。",
    sssi: "Ardley Cutting and Quarry 特别科学价值地点",
    rules: ["只在 BBOWT 保护区内活动，远离开采区。", "不得敲击或采样受保护岩壁。", "移走地质材料前取得 BBOWT 许可。", "恐龙足迹保持原位。"],
    source: "Berks, Bucks & Oxon Wildlife Trust",
  },
  "kirtlington-quarry": {
    region: "牛津郡 · Cherwell Valley",
    period: "中侏罗世",
    type: "地方自然保护区与 SSSI",
    level: "科研敏感地点 · 采集前需许可",
    local: "乘巴士或出租车前往 Kirtlington village",
    walk: "沿公共步道进入地方自然保护区",
    duration: "1小时55分–2小时40分",
    route: ["从 Kirtlington village 经公共保护区入口前往。", "沿既有路径行走，只观察剖面，不切入岩层。", "任何采样或移走化石前联系地点管理方／地方政府。", "异常脊椎动物材料应记录并留在原位等待指导。"],
    terrain: "废弃采石场步道 · 灌丛 · 不平整石灰岩地面",
    exit: "地方自然保护区公共入口",
    tideWindow: "不受潮汐影响",
    season: "干燥白天前往",
    conditions: "植被和剖面可见度会随季节变化",
    findTips: ["科研样本中可能出现重要微型牙齿。", "微小牙齿需要受控筛选和许可。", "不得移走，应拍照并联系管理方。", "科研级材料需要受控发掘。"],
    required: ["保护区地图", "防滑靴", "如需采样则带书面许可", "相机"],
    useful: ["手持放大镜", "记录本", "管理方联系方式"],
    avoid: ["未经许可筛选", "挖掘岩壁", "移走脊椎动物材料", "离开步道"],
    hazards: ["不平整采石场地面", "灌丛遮挡边缘", "受保护科研地层", "脆弱微化石"],
    safetyLead: "Kirtlington 同时是地方自然保护区和全球重要科研地点；公共通行不等于可以随意采集。",
    sssi: "Kirtlington Quarry SSSI 与地方自然保护区",
    rules: ["只使用公共保护区入口。", "未经管理方许可不得挖掘或筛选。", "重要科研发现留在原位。", "遵守全部 SSSI 与保护区告示。"],
    source: "牛津郡议会 · Natural England 指定资料",
  },
  "woodeaton-quarry": {
    region: "牛津郡 · Oxford 东北部",
    period: "中侏罗世",
    type: "私人废弃采石场与 SSSI",
    level: "不允许随意进入 · 仅限获批科研",
    local: "无公共采石场路线；必须先与土地所有者安排通行",
    walk: "未获许可时只能在合法公共通行权范围外部观察",
    duration: "1小时45分–2小时20分",
    route: ["不要把这里当作可直接进入的公共采集点。", "规划任何野外工作前取得土地所有者和管理方书面许可。", "未获许可时只停留在采石场外合法公共通行权范围。", "严禁进入不稳定岩壁、回填区或运输道路。"],
    terrain: "不稳定废弃采石场 · 回填施工区",
    exit: "无公共采石场入口",
    tideWindow: "不受潮汐影响",
    season: "仅限事先约定的科研访问",
    conditions: "通行与回填活动可能变化",
    findTips: ["White Limestone 与 Forest Marble 地层中有腕足类记录。", "脊椎动物层具有科研敏感性。", "采样需要明确科研许可。", "通过获批野外工作负责人报告材料。"],
    required: ["土地所有者书面许可", "地点专项安全说明", "安全帽", "高可见度服装"],
    useful: ["研究计划", "野外记录本", "博物馆联系人"],
    avoid: ["随意进入", "单独前往", "不稳定岩壁", "回填车辆"],
    hazards: ["陡峭不稳定坡面", "活动回填", "私人通行限制", "退化的 SSSI 岩壁"],
    safetyLead: "Woodeaton Quarry 不是公共化石采集点；除非土地所有者明确授权，否则只把它作为科研资料地点。",
    sssi: "Woodeaton Quarry SSSI · 私人土地",
    rules: ["公众不得随意进入采石场。", "必须取得土地所有者书面许可。", "采样可能还需要 SSSI 许可。", "远离运输道路和不稳定岩壁。"],
    source: "牛津郡议会 · GeoGuide",
  },
  whitby: {
    region: "北约克郡 · 约克郡海岸",
    period: "早侏罗世",
    type: "页岩崖与潮间带",
    level: "仅建议有经验成人 · 潮汐决定行程",
    local: "步行穿过镇区前往 East Pier",
    walk: "从车站步行 15–25 分钟，之后沿潮汐控制的前滩行进",
    duration: "4小时15分–5小时15分",
    route: ["到达 East Pier 后，等待前滩路线安全开放。", "在松散页岩、砾石和自然脱落的菱铁矿结核中搜索。", "远离崖面、新鲜滑坡和黏稠地面。", "潮水转向前返回；海水会到达崖脚。"],
    terrain: "页岩 · 巨石 · 湿滑前滩",
    exit: "East Pier 路线；高潮时无安全出口",
    tideWindow: "通常高潮后 3–4 小时才可进入；务必提早返回",
    season: "稳定天气；冬季冲刷只适合有经验成人",
    conditions: "风暴会暴露化石，也会显著增加崖壁危险",
    findTips: ["圆形菱铁矿结核边缘常隐约可见带肋螺旋。", "光滑方解石鞘会从深色页岩中风化出来。", "植物层保存碳膜，煤玉可见木质纹理。", "发现鱼龙或蛇颈龙材料时应记录、保护并报告。"],
    required: ["潮汐计划", "安全帽", "防滑防水靴", "护目镜", "饮用水"],
    useful: ["处理松散结核的地质锤", "扁凿", "硬质标本盒"],
    avoid: ["敲击基岩", "靠近崖面", "携带幼童", "过晚返程"],
    hazards: ["潮水阻断", "崖体坍塌", "黏稠滑坡", "湿滑页岩与巨石"],
    safetyLead: "潮水会抵达崖脚，高水位时没有安全路线。这里不适合幼童，应设定保守的折返时间。",
    sssi: "Whitby–Saltwick 特别科学价值地点",
    rules: ["不得敲击基岩。", "只在远离崖壁处处理松散前滩结核。", "常见材料适量采集。", "海生爬行动物等重要发现应报告。"],
    source: "UK Fossils · Whitby 野外指南",
  },
  "lyme-regis": {
    region: "多塞特郡 · 侏罗纪海岸",
    period: "早侏罗世",
    type: "悬崖与潮间带",
    level: "化石适合新手 · 首次建议导览",
    local: "乘巴士或出租车到 Lyme Regis，再步行到 Monmouth Beach 或 East Beach",
    walk: "从镇中心按所选海滩步行 10–25 分钟",
    duration: "3小时15分–4小时",
    route: ["当天只选一段：Monmouth Beach 或 East Beach／Black Ven 一侧。", "使用镇区正式海滩入口，第一次前往建议参加博物馆导览。", "远离崖脚和活动滑坡，只搜索松散海滩材料。", "高潮阻断岬角和海墙通道前返回。"],
    terrain: "砾石 · 岩台 · 黏稠滑坡黏土",
    exit: "镇区海滩入口；让 Cobb 或海墙保持可见",
    tideWindow: "退潮至低潮时段",
    season: "全年稳定天气；冬季只建议有经验者",
    conditions: "导览可显著提高安全性与辨认成功率",
    findTips: ["松散石灰岩结核和岩板中常见带肋螺旋。", "海滩石块间寻找光滑子弹状鞘。", "Gryphaea 等贝壳会从松散 Blue Lias 岩块中风化出来。", "脊椎动物发现应保护并报告 Lyme Regis Museum。"],
    required: ["潮汐计划", "防滑靴", "安全帽", "饮用水", "包裹材料"],
    useful: ["导览预约", "手持放大镜", "当地允许时用于松散海滩岩块的小锤"],
    avoid: ["挖掘崖壁", "站在滑坡下方", "敲击基岩", "过晚绕过岬角"],
    hazards: ["大型崖体坍塌", "活动滑坡", "潮水阻断", "湿滑岩台"],
    safetyLead: "在开阔前滩采集，不要站在崖下。Lyme 与 Charmouth 同属活动滑坡海岸，强烈建议第一次参加导览。",
    sssi: "West Dorset 海岸 SSSI · 侏罗纪海岸世界遗产",
    rules: ["只采集崩落或海滩松散材料。", "严禁挖掘崖壁或敲击基岩。", "遵守 West Dorset 化石采集守则。", "重要脊椎动物发现应报告博物馆。"],
    source: "Lyme Regis Museum · West Dorset 化石守则 · UK Fossils",
  },
};
