export type DocumentLocationTranslation = {
  region: string;
  period: string;
  type: string;
  level: string;
  local: string;
  walk: string;
  duration: string;
  route: string[];
  terrain: string;
  exit: string;
  tideWindow: string;
  season: string;
  conditions: string;
  findTips: string[];
  required: string[];
  useful: string[];
  avoid: string[];
  hazards: string[];
  safetyLead: string;
  sssi: string;
  rules: string[];
  source: string;
};

type DocumentFind = {
  glyph: string;
  category: string;
  name: string;
  zh: string;
  rarity: string;
  size: string;
  tip: string;
};

export type DocumentLocation = {
  id: string;
  name: string;
  shortName: string;
  region: string;
  period: string;
  age: string;
  type: string;
  risk: "LOW" | "MODERATE" | "HIGH";
  level: string;
  findRating: number;
  accessRating: number;
  familyRating: number;
  mapX: number;
  mapY: number;
  departure: string;
  station: string;
  local: string;
  walk: string;
  duration: string;
  railLink: string;
  mapsLink: string;
  tideLink?: string;
  route: string[];
  terrain: string;
  exit: string;
  tideWindow: string;
  season: string;
  conditions: string;
  finds: DocumentFind[];
  required: string[];
  useful: string[];
  avoid: string[];
  hazards: string[];
  safetyLead: string;
  sssi: string;
  rules: string[];
  source: string;
  sourceLink: string;
  verified: string;
  accent: string;
};

export const documentLocations: DocumentLocation[] = [
  {
    id: "nacton",
    name: "Nacton Shore",
    shortName: "Nacton",
    region: "Suffolk · River Orwell",
    period: "Eocene & Pleistocene",
    age: "c. 55 million years & younger glacial deposits",
    type: "Estuary foreshore",
    risk: "HIGH",
    level: "Cautious adults · low-tide only",
    findRating: 2,
    accessRating: 3,
    familyRating: 1,
    mapX: 88.4,
    mapY: 69.8,
    departure: "London Liverpool Street",
    station: "Ipswich",
    local: "Taxi toward Orwell Park School / Nacton Shore",
    walk: "Short woodland path from the formal shore access",
    duration: "2 hr 10–2 hr 45",
    railLink: "https://www.nationalrail.co.uk/destinations/trains-from-london-to-ipswich/",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=52.00619,1.22373",
    tideLink: "https://www.tidetimes.org.uk/ipswich-tide-times",
    route: [
      "Use the public access near Orwell Park and follow the woodland path to the shore.",
      "Stay on firm shingle and the narrow exposed foreshore; do not step onto the outer mudflats.",
      "Search loose London Clay blocks and glacial flints near the small cliff.",
      "Return before the rising tide covers the firmer line back to the access path.",
    ],
    terrain: "Woodland path · shingle · soft estuary clay",
    exit: "Same woodland access; keep it marked",
    tideWindow: "Falling tide; leave a generous return margin",
    season: "Drier months and settled weather",
    conditions: "Avoid after heavy rain or when mud is waterlogged",
    finds: [
      { glyph: "▲", category: "Shark Teeth", name: "Shark tooth", zh: "鲨鱼牙", rarity: "Occasional", size: "3–30 mm", tip: "Check fine shingle and washed clay for glossy enamel." },
      { glyph: "◈", category: "Fish", name: "Fish remain", zh: "鱼类遗骸", rarity: "Rare", size: "2–30 mm", tip: "Look for small teeth, scales and vertebrae in loose clay." },
      { glyph: "◇", category: "Reptile", name: "Reptile fragment", zh: "爬行动物碎片", rarity: "Very rare", size: "Varies", tip: "Photograph the context and report significant bone." },
      { glyph: "✣", category: "Echinoderms", name: "Flint echinoid or sponge", zh: "燧石海胆或海绵", rarity: "Occasional", size: "2–10 cm", tip: "Glacial flints may preserve five-fold tests or porous sponge texture." },
    ],
    required: ["Tide plan", "Wellington boots", "Walking pole", "Phone", "Water"],
    useful: ["Hand lens", "Small specimen boxes", "Gloves"],
    avoid: ["Outer mudflats", "Cliff digging", "Bedrock hammering", "Visiting alone"],
    hazards: ["Deep sticky mud", "Rapidly returning estuary tide", "Fallen trees", "Soft clay concealed by algae"],
    safetyLead: "The mudflats are the main hazard and have caused a fatal entrapment. Stay on firm ground, go with another person and turn back early.",
    sssi: "Nacton Meadows SSSI",
    rules: ["Collect loose material only.", "Do not hammer bedrock or dig into the cliff.", "Stay off the outer mudflats.", "Current signs and landowner directions take priority."],
    source: "UK Fossils · Nacton field guide",
    sourceLink: "https://ukfossils.co.uk/nacton/",
    verified: "16 Sep 2026",
    accent: "#6bb8ae",
  },
  {
    id: "fort-victoria",
    name: "Fort Victoria",
    shortName: "Fort Victoria",
    region: "Isle of Wight · West Wight",
    period: "Late Eocene",
    age: "c. 35–33 million years",
    type: "Tidal beach & shingle",
    risk: "MODERATE",
    level: "Beginner friendly · guided option",
    findRating: 3,
    accessRating: 5,
    familyRating: 5,
    mapX: 64.8,
    mapY: 90.6,
    departure: "London Waterloo",
    station: "Lymington Pier",
    local: "Ferry to Yarmouth, then bus, taxi or a 30–40 min walk",
    walk: "Short signed descent inside Fort Victoria Country Park",
    duration: "3 hr 15–4 hr",
    railLink: "https://www.nationalrail.co.uk/destinations/trains-from-london-to-lymington-pier/",
    mapsLink: "https://www.google.com/maps/dir/Yarmouth+Ferry+Terminal/Fort+Victoria+Country+Park",
    tideLink: "https://www.tidetimes.org.uk/yarmouth-isle-of-wight-tide-times",
    route: [
      "From Yarmouth, follow the coastal route or use local transport to Fort Victoria Country Park.",
      "Use the signed park path to the tidal beach.",
      "Search loose shingle, clay and the tideline for small vertebrate and shell material.",
      "Leave the beach before the tide reduces the usable shore width.",
    ],
    terrain: "Park paths · shingle · slippery clay patches",
    exit: "Signed country-park beach access",
    tideWindow: "Falling tide through low water",
    season: "Year-round in calm weather",
    conditions: "A guided walk is the easiest first visit",
    finds: [
      { glyph: "◇", category: "Reptile", name: "Crocodile or turtle fragment", zh: "鳄类或龟类碎片", rarity: "Rare", size: "5–50 mm", tip: "Look for dense, pitted bone among dark beach fragments." },
      { glyph: "◈", category: "Fish", name: "Fish tooth or scale", zh: "鱼牙或鱼鳞", rarity: "Occasional", size: "2–20 mm", tip: "Small glossy pieces stand out in fine shingle." },
      { glyph: "◒", category: "Bivalves & Brachiopods", name: "Mollusc shell", zh: "软体动物贝壳", rarity: "Common", size: "1–6 cm", tip: "Handle the thin Eocene shells carefully." },
      { glyph: "✦", category: "Vertebrates", name: "Small mammal remain", zh: "小型哺乳动物遗骸", rarity: "Very rare", size: "2–20 mm", tip: "Record and report unusual teeth or bone before cleaning." },
    ],
    required: ["Tide plan", "Grippy footwear", "Small specimen pots", "Water"],
    useful: ["Hand lens", "Tweezers", "Guided-walk booking"],
    avoid: ["Swimming", "Strong-current margins", "Digging the cliff"],
    hazards: ["Strong tidal currents", "Slippery clay", "Narrowing beach", "Fragile specimens"],
    safetyLead: "The country park is easy to reach, but the beach is tidal and the currents off Fort Victoria are strong. Do not swim and keep children close.",
    sssi: "Headon Warren and West High Down SSSI coastline",
    rules: ["Prefer loose foreshore finds.", "Do not excavate cliffs or protected beds.", "Follow country-park notices and ranger instructions.", "Report unusual vertebrate material."],
    source: "UK Fossils · Isle of Wight Council",
    sourceLink: "https://ukfossils.co.uk/fort-victoria/",
    verified: "16 Sep 2026",
    accent: "#5fbfd0",
  },
  {
    id: "barton-on-sea",
    name: "Barton-on-Sea",
    shortName: "Barton-on-Sea",
    region: "Hampshire · Christchurch Bay",
    period: "Middle–Late Eocene",
    age: "c. 41–37 million years",
    type: "Clay cliff & foreshore",
    risk: "HIGH",
    level: "Beginner finds · serious cliff risk",
    findRating: 5,
    accessRating: 4,
    familyRating: 3,
    mapX: 66.5,
    mapY: 89.8,
    departure: "London Waterloo",
    station: "New Milton",
    local: "Local bus or taxi to Barton cliff-top",
    walk: "10–20 min via a formal beach access",
    duration: "2 hr 15–2 hr 50",
    railLink: "https://www.nationalrail.co.uk/destinations/trains-from-london-to-new-milton/",
    mapsLink: "https://www.google.com/maps/dir/New+Milton+Station/Barton+on+Sea+Beach",
    tideLink: "https://www.tidetimes.org.uk/barton-on-sea-tide-times",
    route: [
      "Use a formal cliff-top path and marked beach access.",
      "Stay at beach level and search loose clay, shingle and wave-washed slips.",
      "Wrap fragile shells as soon as they are found.",
      "Return before high water and never use a fresh landslip as a shortcut.",
    ],
    terrain: "Steps or slope · shingle · sticky clay",
    exit: "Formal cliff-top access used on arrival",
    tideWindow: "Falling tide; avoid storm surge",
    season: "Spring–autumn; avoid wet storm periods",
    conditions: "Productive after gentle erosion once slips have settled",
    finds: [
      { glyph: "◒", category: "Gastropods", name: "Gastropod shell", zh: "腹足类贝壳", rarity: "Very common", size: "1–8 cm", tip: "Fine ribs and spires can be exposed in soft clay." },
      { glyph: "◒", category: "Bivalves & Brachiopods", name: "Bivalve shell", zh: "双壳类", rarity: "Common", size: "1–10 cm", tip: "Lift loose shells with surrounding clay and wrap immediately." },
      { glyph: "▲", category: "Shark Teeth", name: "Shark tooth", zh: "鲨鱼牙", rarity: "Rare", size: "3–30 mm", tip: "Check fine shingle below eroded clay." },
      { glyph: "◈", category: "Fish", name: "Fish remain", zh: "鱼类遗骸", rarity: "Occasional", size: "2–30 mm", tip: "Look for glossy teeth and vertebrae in loose material." },
    ],
    required: ["Tide plan", "Grippy boots", "Tissue", "Rigid boxes", "Water"],
    useful: ["Small trowel", "Hand lens", "Knee pads"],
    avoid: ["Climbing slips", "Standing below cliffs", "Heavy rain visits", "Digging the cliff"],
    hazards: ["Frequent cliff falls", "Deep sticky clay", "Rising tide", "Very fragile shells"],
    safetyLead: "Stay at beach level and well away from the cliff base. The clay landslips can move without warning, especially after rain.",
    sssi: "Highcliffe to Milford Cliffs SSSI",
    rules: ["Collect loose, naturally eroded material only.", "Do not climb or dig into the cliff.", "Take only modest quantities of fragile shells.", "Follow current local notices."],
    source: "UK Fossils · Barton-on-Sea field guide",
    sourceLink: "https://ukfossils.co.uk/barton-on-sea/",
    verified: "16 Sep 2026",
    accent: "#d7a45d",
  },
  {
    id: "warden-point",
    name: "Warden Point",
    shortName: "Warden Point",
    region: "Kent · Isle of Sheppey",
    period: "Early Eocene",
    age: "c. 54–52 million years",
    type: "London Clay foreshore",
    risk: "HIGH",
    level: "Experienced tide planner",
    findRating: 4,
    accessRating: 3,
    familyRating: 2,
    mapX: 87.2,
    mapY: 80.4,
    departure: "London Victoria or St Pancras",
    station: "Sheerness-on-Sea",
    local: "Bus or taxi toward Warden / Leysdown",
    walk: "Use the public beach access and walk the open foreshore",
    duration: "2 hr 30–3 hr 15",
    railLink: "https://www.nationalrail.co.uk/destinations/trains-from-london-to-sheerness-on-sea/",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Warden+Point+Isle+of+Sheppey",
    tideLink: "https://www.tidetimes.org.uk/sheerness-tide-times",
    route: [
      "Approach from the public beach access at Warden Bay.",
      "Search loose nodules, shingle and clay platforms without working the cliff face.",
      "Avoid exposed mud and old wreckage, even when they appear to shorten the route.",
      "Turn around while the beach is still broad and the access remains obvious.",
    ],
    terrain: "Shingle · clay platform · sticky mud",
    exit: "Public Warden Bay beach access",
    tideWindow: "Falling tide to low water; return early",
    season: "Settled spring–autumn days",
    conditions: "Avoid immediately after heavy rain or major cliff falls",
    finds: [
      { glyph: "▲", category: "Shark Teeth", name: "Shark tooth", zh: "鲨鱼牙", rarity: "Occasional", size: "3–40 mm", tip: "Search washed shingle and the edges of loose clay." },
      { glyph: "⌁", category: "Crabs", name: "Crab or lobster", zh: "螃蟹或龙虾", rarity: "Occasional", size: "1–10 cm", tip: "Concretions may preserve carapaces and claws." },
      { glyph: "◇", category: "Reptile", name: "Turtle or crocodile remain", zh: "龟类或鳄类遗骸", rarity: "Rare", size: "Varies", tip: "Pitted bone should be photographed and reported." },
      { glyph: "⌇", category: "Plant Fossils", name: "Plant remain", zh: "植物遗骸", rarity: "Occasional", size: "1–15 cm", tip: "Look for seeds, wood grain and leaf fragments in nodules." },
    ],
    required: ["Tide plan", "Wellington boots", "Phone", "Gloves", "Water"],
    useful: ["Walking pole", "Hand lens", "Specimen boxes"],
    avoid: ["Cliff digging", "Outer mud", "Old wreck metal", "Visiting alone"],
    hazards: ["Cliff falls", "Deep sticky mud", "Sharp wreck debris", "Tidal cut-off"],
    safetyLead: "Keep clear of cliffs, mudflats and sharp wreck material. The safest plan is a conservative low-tide visit with an early turn-around.",
    sssi: "Sheppey Cliffs and Foreshore SSSI",
    rules: ["Do not dig into cliffs or hammer bedrock.", "Collect loose foreshore material only.", "Avoid vegetation and wildlife disturbance.", "Report scientifically important vertebrate finds."],
    source: "UK Fossils · Warden Point field guide",
    sourceLink: "https://ukfossils.co.uk/warden-point/",
    verified: "16 Sep 2026",
    accent: "#5f9eb0",
  },
  {
    id: "abbey-wood",
    name: "Abbey Wood / Lesnes Abbey",
    shortName: "Abbey Wood",
    region: "Greater London · Bexley",
    period: "Late Palaeocene–Early Eocene",
    age: "c. 55 million years",
    type: "Managed inland fossil bed",
    risk: "LOW",
    level: "Permission required · family friendly",
    findRating: 5,
    accessRating: 5,
    familyRating: 5,
    mapX: 79.2,
    mapY: 79.8,
    departure: "London Elizabeth line / National Rail",
    station: "Abbey Wood",
    local: "Walk toward Lesnes Abbey Woods",
    walk: "15–25 min from Abbey Wood station",
    duration: "45 min–1 hr 20",
    railLink: "https://www.nationalrail.co.uk/destinations/trains-from-london-to-abbey-wood/",
    mapsLink: "https://www.google.com/maps/dir/Abbey+Wood+Station/Lesnes+Abbey+Woods",
    route: [
      "Contact Bexley Parks & Open Spaces before collecting and wait for permission.",
      "Walk from Abbey Wood station to Lesnes Abbey Woods using public paths.",
      "Use only the designated fossil bed and follow the ranger's current instructions.",
      "Keep excavations shallow, refill every hole and take no more material than allowed.",
    ],
    terrain: "Park paths · soil excavation area",
    exit: "Return by Lesnes Abbey park paths",
    tideWindow: "Tide not applicable",
    season: "By permission; avoid waterlogged ground",
    conditions: "Best as a ranger-approved or organised visit",
    finds: [
      { glyph: "▲", category: "Shark Teeth", name: "Shark tooth", zh: "鲨鱼牙", rarity: "Very common", size: "2–25 mm", tip: "Wet-sieving the permitted shell bed reveals small dark teeth." },
      { glyph: "◈", category: "Fish", name: "Fish tooth or scale", zh: "鱼牙或鱼鳞", rarity: "Common", size: "1–15 mm", tip: "Use fine mesh and tweezers for tiny glossy material." },
      { glyph: "◇", category: "Reptile", name: "Turtle or crocodile fragment", zh: "龟类或鳄类碎片", rarity: "Rare", size: "3–40 mm", tip: "Pitted bone and armour fragments should be recorded." },
      { glyph: "✦", category: "Vertebrates", name: "Mammal or bird tooth", zh: "哺乳动物或鸟类牙骨", rarity: "Very rare", size: "1–8 mm", tip: "Major finds must be handed to the local museum for research." },
    ],
    required: ["Written permission", "0.5 mm sieve", "Bucket", "Tweezers", "Sample pots"],
    useful: ["Water basin", "Two sieve grades", "Kneeling mat"],
    avoid: ["Unapproved visits", "Digging deeper than 2 ft", "Taking more than 2 kg", "Leaving holes open"],
    hazards: ["Open excavation holes", "Slippery ground", "Tiny fragile specimens", "Protected scientific site"],
    safetyLead: "This is a managed public fossil bed, not a casual digging spot. Obtain permission first and follow the ranger's limits exactly.",
    sssi: "Abbey Wood SSSI",
    rules: ["Obtain prior permission from Bexley Parks & Open Spaces.", "Do not dig deeper than 2 ft.", "Refill all holes and remove no more than 2 kg of material.", "Hand major finds to the local museum for research."],
    source: "UK Fossils · Natural England Abbey Wood citation",
    sourceLink: "https://ukfossils.co.uk/abbey-wood/",
    verified: "16 Sep 2026",
    accent: "#8dac75",
  },
  {
    id: "grange-chine",
    name: "Grange Chine / Brighstone Bay",
    shortName: "Grange Chine",
    region: "Isle of Wight · South-west coast",
    period: "Early Cretaceous",
    age: "c. 130–125 million years",
    type: "Dinosaur coast foreshore",
    risk: "HIGH",
    level: "Guided first visit recommended",
    findRating: 4,
    accessRating: 3,
    familyRating: 3,
    mapX: 66.1,
    mapY: 92.4,
    departure: "London Waterloo",
    station: "Portsmouth Harbour",
    local: "Ferry to Ryde or West Cowes, then island bus / taxi to Brighstone",
    walk: "Steep public path through Grange Farm to the beach",
    duration: "4 hr–5 hr",
    railLink: "https://www.nationalrail.co.uk/destinations/trains-from-london-to-portsmouth-harbour/",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Grange+Chine+Brighstone",
    tideLink: "https://www.tidetimes.org.uk/freshwater-bay-tide-times",
    route: [
      "Reach Grange Farm by the A3055 / island bus corridor and use only legitimate parking.",
      "Follow the public footpath through the chine; the final slope is steep.",
      "Search loose foreshore material and the plant-debris bed east of the chine.",
      "Return before high water reduces the beach around the headlands.",
    ],
    terrain: "Steep slope · shingle · clay ledges",
    exit: "Public footpath through Grange Farm",
    tideWindow: "Falling tide through low water",
    season: "Spring–autumn in settled weather",
    conditions: "Guided walks help with access and identification",
    finds: [
      { glyph: "◇", category: "Reptile", name: "Dinosaur bone or tooth", zh: "恐龙骨骼或牙齿", rarity: "Rare", size: "Varies", tip: "Dense black bone may show a honeycomb interior; record context." },
      { glyph: "⌇", category: "Plant Fossils", name: "Fossil wood", zh: "化石木", rarity: "Common", size: "1–30 cm", tip: "Plant debris beds contain grain-textured fragments." },
      { glyph: "◈", category: "Fish", name: "Fish or hybodont tooth", zh: "鱼类或弓鲛牙齿", rarity: "Occasional", size: "2–25 mm", tip: "Check fine debris on hard plant-bed surfaces." },
      { glyph: "◇", category: "Reptile", name: "Crocodile or turtle fragment", zh: "鳄类或龟类碎片", rarity: "Rare", size: "5–60 mm", tip: "Pitted plates and dense bone need careful recording." },
    ],
    required: ["Tide plan", "Grippy boots", "Water", "Phone", "Rigid specimen box"],
    useful: ["Hand lens", "Guided-walk booking", "Walking poles"],
    avoid: ["Cliff digging", "Standing below fresh falls", "Unapproved parking", "High-water headlands"],
    hazards: ["Steep beach access", "Cliff falls", "Tidal cut-off", "Uneven clay ledges"],
    safetyLead: "The public path is usable but steep, and the beach has unstable cliffs. Keep away from the cliff base and plan the return around low water.",
    sssi: "Compton Chine to Steephill Cove SSSI",
    rules: ["Collect loose foreshore material only.", "Do not excavate cliffs or in-situ dinosaur beds.", "Use the public footpath and legitimate parking.", "Report important dinosaur material to Dinosaur Isle."],
    source: "Island Rivers · Wight Coast Fossils · GeoGuide",
    sourceLink: "https://islandrivers.org.uk/chines/explore-the-chines/grange-and-marsh/",
    verified: "16 Sep 2026",
    accent: "#c57c61",
  },
  {
    id: "hastings",
    name: "Hastings / Rock-a-Nore",
    shortName: "Hastings",
    region: "East Sussex · Hastings coast",
    period: "Early Cretaceous",
    age: "c. 140–136 million years",
    type: "Cliff & foreshore",
    risk: "HIGH",
    level: "Experienced collector",
    findRating: 3,
    accessRating: 4,
    familyRating: 2,
    mapX: 81.8,
    mapY: 89.7,
    departure: "London Charing Cross or London Bridge",
    station: "Hastings",
    local: "Walk or local bus to Rock-a-Nore in the Old Town",
    walk: "20–30 min from Hastings station",
    duration: "2 hr–2 hr 30",
    railLink: "https://www.nationalrail.co.uk/destinations/trains-from-london-to-hastings/",
    mapsLink: "https://www.google.com/maps/dir/Hastings+Station/Rock-a-Nore+Road",
    tideLink: "https://www.tidetimes.org.uk/hastings-tide-times",
    route: [
      "Reach Rock-a-Nore through Hastings Old Town and use the formal seafront access.",
      "Search the open foreshore for loose clay blocks, teeth, shells and plant material.",
      "Do not enter scree or work below the high sandstone cliffs.",
      "Return toward Rock-a-Nore well before the tide narrows the route.",
    ],
    terrain: "Shingle · clay patches · rock platforms",
    exit: "Rock-a-Nore seafront access",
    tideWindow: "Falling tide after safe scouring",
    season: "Autumn–spring in settled conditions",
    conditions: "Finds depend strongly on beach scour after storms",
    finds: [
      { glyph: "◇", category: "Reptile", name: "Dinosaur bone or footprint", zh: "恐龙骨骼或足迹", rarity: "Rare", size: "Varies", tip: "Photograph footprints in place; record loose dense bone." },
      { glyph: "◈", category: "Fish", name: "Fish remain", zh: "鱼类遗骸", rarity: "Occasional", size: "3–50 mm", tip: "Hard clay blocks can contain teeth, scales and bone." },
      { glyph: "▲", category: "Shark Teeth", name: "Hybodont tooth", zh: "弓鲛牙齿", rarity: "Rare", size: "2–25 mm", tip: "Look for small glossy crowns in washed clay." },
      { glyph: "⌇", category: "Plant Fossils", name: "Plant remain", zh: "植物遗骸", rarity: "Common", size: "1–20 cm", tip: "Carbonised stems and wood occur in loose blocks." },
    ],
    required: ["Tide plan", "Hard hat", "Grippy boots", "Eye protection", "Water"],
    useful: ["Hand lens", "Specimen boxes", "Camera with scale"],
    avoid: ["Cliff base", "Scree slopes", "Fresh falls", "Rising-tide headlands"],
    hazards: ["Very high unstable cliffs", "Falling rock", "Slippery platforms", "Tidal cut-off"],
    safetyLead: "Rock-a-Nore is geologically important but the cliff line is dangerous. Search only loose foreshore material and keep a wide distance from the cliff base.",
    sssi: "Hastings Cliffs to Pett Beach SSSI",
    rules: ["Collect only loose foreshore material.", "Do not dig into cliffs, scree or bedrock.", "Photograph trace fossils in place.", "Report significant dinosaur or vertebrate finds."],
    source: "UK Fossils · Hastings field guide",
    sourceLink: "https://ukfossils.co.uk/hastings/",
    verified: "16 Sep 2026",
    accent: "#b8735f",
  },
  {
    id: "ardley-quarry",
    name: "Ardley Wood Quarry",
    shortName: "Ardley",
    region: "Oxfordshire · Near Bicester",
    period: "Middle Jurassic",
    age: "c. 167 million years",
    type: "Nature reserve & quarry exposure",
    risk: "MODERATE",
    level: "Geology visit · collecting permission needed",
    findRating: 3,
    accessRating: 4,
    familyRating: 3,
    mapX: 69.9,
    mapY: 74.2,
    departure: "London Marylebone",
    station: "Bicester North",
    local: "Taxi to the BBOWT Ardley Wood Quarry entrance",
    walk: "Network of short, undulating reserve paths",
    duration: "1 hr 35–2 hr 10",
    railLink: "https://www.nationalrail.co.uk/destinations/trains-from-london-to-bicester-north/",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Ardley+Wood+Quarry+OX27+7NU",
    route: [
      "Visit the public BBOWT nature reserve, not the neighbouring active quarry.",
      "Use the signed reserve paths and keep away from steep embankments and exposed faces.",
      "Treat this as a geology-observation visit unless BBOWT gives explicit collecting permission.",
      "Leave every protected exposure and fossil trace undisturbed.",
    ],
    terrain: "Firm undulating paths · steep southern embankment",
    exit: "Return to the reserve entrance by the railway bridge",
    tideWindow: "Tide not applicable",
    season: "Open year-round; best in dry daylight",
    conditions: "Reserve paths may be uneven after rain",
    finds: [
      { glyph: "◒", category: "Bivalves & Brachiopods", name: "Brachiopod or bivalve", zh: "腕足类或双壳类", rarity: "Common", size: "1–8 cm", tip: "Observe shells in loose limestone without disturbing faces." },
      { glyph: "◈", category: "Fish", name: "Fish remain", zh: "鱼类遗骸", rarity: "Rare", size: "2–30 mm", tip: "Small vertebrate material is scientifically important." },
      { glyph: "▲", category: "Shark Teeth", name: "Hybodont tooth", zh: "弓鲛牙齿", rarity: "Very rare", size: "2–20 mm", tip: "Do not remove material without written permission." },
      { glyph: "◇", category: "Trace Fossils", name: "Dinosaur track", zh: "恐龙足迹", rarity: "Very rare", size: "Large", tip: "Tracks are protected features: view and photograph only." },
    ],
    required: ["Reserve map", "Grippy boots", "Phone", "Written permission if sampling"],
    useful: ["Binoculars", "Camera", "Hand lens"],
    avoid: ["Active quarry", "Rock faces", "Sampling without permission", "Disturbing wildlife"],
    hazards: ["Steep embankments", "Uneven quarry floor", "Protected exposures", "Nearby active workings"],
    safetyLead: "The public reserve is open, but that does not automatically permit fossil collecting. Stay inside the reserve and obtain written permission before removing geological material.",
    sssi: "Ardley Cutting and Quarry SSSI",
    rules: ["Stay on the BBOWT reserve and out of active workings.", "Do not hammer or sample protected faces.", "Seek BBOWT permission before removing geological material.", "Leave dinosaur traces in place."],
    source: "Berks, Bucks & Oxon Wildlife Trust",
    sourceLink: "https://www.bbowt.org.uk/nature-reserves/ardley-wood-quarry",
    verified: "16 Sep 2026",
    accent: "#91a86f",
  },
  {
    id: "kirtlington-quarry",
    name: "Kirtlington Quarry",
    shortName: "Kirtlington",
    region: "Oxfordshire · Cherwell Valley",
    period: "Middle Jurassic",
    age: "c. 166 million years",
    type: "Local nature reserve & SSSI",
    risk: "MODERATE",
    level: "Research-sensitive · permission before collecting",
    findRating: 5,
    accessRating: 3,
    familyRating: 3,
    mapX: 69.1,
    mapY: 75.3,
    departure: "London Paddington or Marylebone",
    station: "Oxford Parkway",
    local: "Bus or taxi toward Kirtlington village",
    walk: "Use public paths into the local nature reserve",
    duration: "1 hr 55–2 hr 40",
    railLink: "https://www.nationalrail.co.uk/destinations/trains-from-london-to-oxford-parkway/",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Kirtlington+Quarry+Local+Nature+Reserve",
    route: [
      "Approach via Kirtlington village and the public nature-reserve access.",
      "Stay on established paths and observe exposures without cutting into them.",
      "Contact the site manager / local authority before any sampling or fossil removal.",
      "Record unusual vertebrate material and leave it in place pending advice.",
    ],
    terrain: "Disused quarry paths · scrub · uneven limestone ground",
    exit: "Public local-nature-reserve access",
    tideWindow: "Tide not applicable",
    season: "Dry daylight visits",
    conditions: "Vegetation and exposure quality vary seasonally",
    finds: [
      { glyph: "▲", category: "Shark Teeth", name: "Micro-shark tooth", zh: "微型鲨鱼牙", rarity: "Occasional", size: "1–8 mm", tip: "The scientifically important teeth occur in research samples." },
      { glyph: "◈", category: "Fish", name: "Fish tooth", zh: "鱼牙", rarity: "Occasional", size: "1–12 mm", tip: "Tiny teeth require controlled sieving and permission." },
      { glyph: "◇", category: "Reptile", name: "Crocodile or dinosaur remain", zh: "鳄类或恐龙遗骸", rarity: "Very rare", size: "Varies", tip: "Do not remove; photograph and contact the site manager." },
      { glyph: "✦", category: "Vertebrates", name: "Mammal microfossil", zh: "哺乳动物微化石", rarity: "Very rare", size: "Under 5 mm", tip: "Research-grade material requires controlled excavation." },
    ],
    required: ["Reserve map", "Grippy boots", "Written permission if sampling", "Camera"],
    useful: ["Hand lens", "Notebook", "Contact details for site manager"],
    avoid: ["Unapproved sieving", "Face excavation", "Removing vertebrate material", "Leaving paths"],
    hazards: ["Uneven quarry ground", "Scrub-obscured edges", "Protected scientific beds", "Fragile microfossils"],
    safetyLead: "Kirtlington is both a local nature reserve and a globally important research site. Public access is not blanket permission to collect.",
    sssi: "Kirtlington Quarry SSSI & Local Nature Reserve",
    rules: ["Use public reserve access only.", "Do not excavate or sieve without site-manager permission.", "Leave scientifically important finds in place.", "Follow all SSSI and local reserve notices."],
    source: "Oxfordshire County Council · Natural England citation",
    sourceLink: "https://owls.oxfordshire.gov.uk/wps/wcm/connect/occ/OWLS/Home/Oxfordshire+Districts/Oxfordshire+Districts+-+Parishes/Cherwell+Parishes/Kirtlington/",
    verified: "16 Sep 2026",
    accent: "#8aa579",
  },
  {
    id: "woodeaton-quarry",
    name: "Woodeaton Quarry",
    shortName: "Woodeaton",
    region: "Oxfordshire · North-east of Oxford",
    period: "Middle Jurassic",
    age: "c. 167–165 million years",
    type: "Private disused quarry & SSSI",
    risk: "HIGH",
    level: "No casual access · research permission only",
    findRating: 5,
    accessRating: 1,
    familyRating: 1,
    mapX: 69.8,
    mapY: 76.6,
    departure: "London Paddington",
    station: "Oxford",
    local: "No public quarry route; arrange access with the landowner first",
    walk: "View only from lawful public rights of way unless permission is granted",
    duration: "1 hr 45–2 hr 20",
    railLink: "https://www.nationalrail.co.uk/destinations/trains-from-london-to-oxford/",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Woodeaton+Oxfordshire",
    route: [
      "Do not travel expecting public quarry entry.",
      "Obtain written landowner and site-management permission before planning any fieldwork.",
      "Without permission, remain on lawful public rights of way outside the quarry.",
      "Never enter unstable faces, restoration areas or haul-road access.",
    ],
    terrain: "Unstable disused quarry · restoration works",
    exit: "No public quarry access",
    tideWindow: "Tide not applicable",
    season: "Research visits by prior agreement only",
    conditions: "Access and restoration activity can change",
    finds: [
      { glyph: "◒", category: "Bivalves & Brachiopods", name: "Brachiopod", zh: "腕足类", rarity: "Common", size: "1–6 cm", tip: "Known from the White Limestone and Forest Marble succession." },
      { glyph: "◈", category: "Fish", name: "Fish remain", zh: "鱼类遗骸", rarity: "Rare", size: "2–30 mm", tip: "Vertebrate beds are scientifically sensitive." },
      { glyph: "▲", category: "Shark Teeth", name: "Hybodont tooth", zh: "弓鲛牙齿", rarity: "Rare", size: "2–25 mm", tip: "Sampling requires explicit research permission." },
      { glyph: "◇", category: "Reptile", name: "Crocodile remain", zh: "鳄类遗骸", rarity: "Very rare", size: "Varies", tip: "Report material through the permitted fieldwork lead." },
    ],
    required: ["Written landowner permission", "Site-specific safety briefing", "Hard hat", "High-visibility clothing"],
    useful: ["Research plan", "Field notebook", "Museum contact"],
    avoid: ["Casual entry", "Solo visits", "Unstable faces", "Restoration traffic"],
    hazards: ["Sheer unstable slopes", "Active restoration", "Private access", "Degraded SSSI faces"],
    safetyLead: "Woodeaton Quarry is not a public fossil-hunting stop. Keep it as a research reference unless the landowner has granted explicit access.",
    sssi: "Woodeaton Quarry SSSI · private land",
    rules: ["No casual public quarry entry.", "Written landowner permission is required.", "SSSI consent may also be needed for sampling.", "Stay off haul roads and unstable faces."],
    source: "Oxfordshire County Council · GeoGuide",
    sourceLink: "https://geoguide.scottishgeologytrust.org/page/2262",
    verified: "16 Sep 2026",
    accent: "#857f68",
  },
  {
    id: "whitby",
    name: "Whitby East Cliff",
    shortName: "Whitby",
    region: "North Yorkshire · Yorkshire coast",
    period: "Early Jurassic",
    age: "c. 183–174 million years",
    type: "Shale cliff & foreshore",
    risk: "HIGH",
    level: "Experienced adults · tide critical",
    findRating: 5,
    accessRating: 3,
    familyRating: 1,
    mapX: 72.1,
    mapY: 46.2,
    departure: "London King's Cross",
    station: "Whitby",
    local: "Walk through town to the East Pier",
    walk: "15–25 min, then tide-dependent foreshore travel",
    duration: "4 hr 15–5 hr 15",
    railLink: "https://www.nationalrail.co.uk/destinations/trains-from-london-to-whitby/",
    mapsLink: "https://www.google.com/maps/dir/Whitby+Station/Whitby+East+Pier",
    tideLink: "https://www.tidetimes.org.uk/whitby-tide-times",
    route: [
      "Reach the East Pier and wait until the foreshore route is safely open.",
      "Search loose shale, shingle and naturally released siderite nodules.",
      "Keep away from cliff faces, fresh slips and sticky ground.",
      "Return before the tide turns; the sea reaches the cliff base.",
    ],
    terrain: "Shale · boulders · slippery foreshore",
    exit: "East Pier route; no high-tide escape",
    tideWindow: "Access often opens 3–4 hours after high tide; return early",
    season: "Settled weather; winter scour only for experienced adults",
    conditions: "Storms expose finds but also increase cliff danger",
    finds: [
      { glyph: "◎", category: "Ammonites & Heteromorphs", name: "Ammonite", zh: "菊石", rarity: "Very common", size: "2–25 cm", tip: "Rounded siderite nodules often show a faint ribbed whorl." },
      { glyph: "│", category: "Other Cephalopods", name: "Belemnite", zh: "箭石", rarity: "Common", size: "2–12 cm", tip: "Smooth calcite guards weather free from dark shale." },
      { glyph: "⌇", category: "Plant Fossils", name: "Fossil plant or jet", zh: "植物化石或煤玉", rarity: "Occasional", size: "1–20 cm", tip: "Plant beds preserve carbon films; jet shows woody texture." },
      { glyph: "◇", category: "Reptile", name: "Marine reptile remain", zh: "海生爬行动物遗骸", rarity: "Very rare", size: "Varies", tip: "Record, protect and report ichthyosaur or plesiosaur material." },
    ],
    required: ["Tide plan", "Hard hat", "Grippy waterproof boots", "Eye protection", "Water"],
    useful: ["Geological hammer for loose nodules", "Flat chisel", "Rigid specimen box"],
    avoid: ["Bedrock hammering", "Cliff face", "Young children", "Late return"],
    hazards: ["Tidal cut-off", "Cliff falls", "Sticky slips", "Slippery shale and boulders"],
    safetyLead: "The tide reaches the cliff base and there is no safe high-water route. This is not a young-child beach; set a conservative return time.",
    sssi: "Whitby–Saltwick SSSI",
    rules: ["Do not hammer bedrock.", "Work only loose foreshore nodules away from cliffs.", "Take modest common material.", "Report marine reptile and other significant finds."],
    source: "UK Fossils · Whitby field guide",
    sourceLink: "https://ukfossils.co.uk/whitby/",
    verified: "16 Sep 2026",
    accent: "#567b8f",
  },
  {
    id: "lyme-regis",
    name: "Lyme Regis / Monmouth Beach",
    shortName: "Lyme Regis",
    region: "Dorset · Jurassic Coast",
    period: "Early Jurassic",
    age: "c. 201–190 million years",
    type: "Cliff & foreshore",
    risk: "HIGH",
    level: "Beginner finds · guided first visit recommended",
    findRating: 5,
    accessRating: 4,
    familyRating: 3,
    mapX: 56.2,
    mapY: 91.1,
    departure: "London Waterloo",
    station: "Axminster",
    local: "Bus or taxi to Lyme Regis, then walk to Monmouth Beach or East Beach",
    walk: "10–25 min from the town centre depending on the chosen beach",
    duration: "3 hr 15–4 hr",
    railLink: "https://www.nationalrail.co.uk/destinations/trains-from-london-to-axminster/",
    mapsLink: "https://www.google.com/maps/dir/Axminster+Station/Lyme+Regis+Museum",
    tideLink: "https://www.tidetimes.org.uk/lyme-regis-tide-times",
    route: [
      "Choose one section for the day: Monmouth Beach or the East Beach / Black Ven side.",
      "Use the town's formal beach access and join a museum-guided walk on a first visit.",
      "Search loose beach material well away from the cliff base and active landslides.",
      "Return before high tide cuts access around headlands and sea walls.",
    ],
    terrain: "Shingle · rock ledges · sticky landslide clay",
    exit: "Town beach access; keep the Cobb or sea wall in sight",
    tideWindow: "Falling tide through low water",
    season: "Year-round in settled weather; winter for experienced collectors",
    conditions: "Guided walks improve safety and identification",
    finds: [
      { glyph: "◎", category: "Ammonites & Heteromorphs", name: "Ammonite", zh: "菊石", rarity: "Very common", size: "2–30 cm", tip: "Loose limestone nodules and slabs often show ribbed coils." },
      { glyph: "│", category: "Other Cephalopods", name: "Belemnite", zh: "箭石", rarity: "Common", size: "2–12 cm", tip: "Look for smooth bullet-shaped guards among beach stones." },
      { glyph: "◒", category: "Bivalves & Brachiopods", name: "Bivalve shell", zh: "双壳类", rarity: "Common", size: "1–12 cm", tip: "Gryphaea and other shells weather from loose Blue Lias blocks." },
      { glyph: "◇", category: "Reptile", name: "Marine reptile remain", zh: "海生爬行动物遗骸", rarity: "Very rare", size: "Varies", tip: "Protect and report vertebrate finds to Lyme Regis Museum." },
    ],
    required: ["Tide plan", "Grippy boots", "Hard hat", "Water", "Wrapping material"],
    useful: ["Guided-walk booking", "Hand lens", "Small hammer for loose beach rock where permitted"],
    avoid: ["Cliff digging", "Standing below landslides", "Hammering bedrock", "Crossing headlands late"],
    hazards: ["Major cliff falls", "Active landslides", "Tidal cut-off", "Slippery rock ledges"],
    safetyLead: "Collect on the open foreshore, not beneath cliffs. Lyme and Charmouth share an active landslide coast, so a guided first visit is strongly recommended.",
    sssi: "West Dorset coast SSSI · Jurassic Coast World Heritage Site",
    rules: ["Collect fallen or beach material only.", "Never dig into cliffs or hammer bedrock.", "Follow the West Dorset Fossil Collecting Code.", "Report important vertebrate finds to the museum."],
    source: "Lyme Regis Museum · West Dorset Fossil Code · UK Fossils",
    sourceLink: "https://www.lymeregismuseum.co.uk/whats-on/fossil-walks/",
    verified: "16 Sep 2026",
    accent: "#4e9a9a",
  },
];
